### ISSUE TITLE
Suggested improvements to live_receiver.py

### ISSUE THREAD

**Issue by svadams** [SpiNNakerManchester/PyNNExamples_OLD#1]
It would be useful to have more comments/explanation in this script of the contents of the packet 
that is printed out. Even better would be to include code for a full packet decode - for example extracting the neuron id from the packet.

**Comment by alan-stokes** [comment]
Hi sam, this has been done via the spike_io.py that can be located in pynnExamples/examples/external_device_examples/spike_io.py 

Rowley did a good chunk of work making a exmaple which ties all the input/output together in one script that should ake things expicit.
