### ISSUE TITLE
add_receive_callback() in spike_io.py

### ISSUE THREAD

**Issue by WemboLi** [SpiNNakerManchester/PyNNExamples_OLD#17]
Dear all, 
When I try to use live_spikes_connection_receive.add_receive_callback( "pop_forward", receive_spikes) to add a call back function for population "pop_forward" in spike_io.py, the call back function "receive_spikes" is never called upon the receival of spikes, although the injection of spikes is successful. I am unclear that whether there is something wrong with configuration of database communication in spike_io.py or parameters settings in spynnaker.cfg in the root directory. As I use the spike_io.py from github for a trial, I just list the spynnaker.cfg settings to see if you could give me some help,

[Machine]
machineName     = 192.168.240.253
version         = 3
# machineTimeStep = 1000
# timeScaleFactor = 1

[Database]
create_database = True
wait_on_confirmation = True
create_routing_info_to_neuron_id_mapping = True
send_start_notification = True

listen_port = 19996
notify_port = 19999
notify_hostname = localhost

[Reports]
reportsEnabled = True
writeTextSpecs = False
writePartitionerReports = True
writePlacerReports = True
writeRouterReports = True
writeRouterInfoReport = True
writeRouterDatReport = False
writeTransceiverReport = True
writeProvanceData = True
writeTagAllocationReports = True
outputTimesForSections = True
writeReloadSteps = True
defaultReportFilePath = DEFAULT
defaultApplicationDataFilePath = DEFAULT
max_reports_kept = 10
max_application_binaries_kept = 10

[Simulation]
spikes_per_second = 30
ring_buffer_sigma = 5

[Routing]

algorithm = BasicDijkstra
generate_graphs = False
graphs_output_file = tmp

[Placer]
algorithm = Radial

[TagAllocator]
algorithm = Basic

[Partitioner]
algorithm = PartitionAndPlace

[KeyAllocator]
algorithm = MallocBased

[SpecExecution]
specExecOnHost = True

[MasterPopTable]
generator = BinarySearch

**Comment by alan-stokes** [comment]
Hi Wembo, 

could you please post this on the spinnaker user google group, as you will have access to the entire community of spinnaker users who can have more expereince with using the spinnaker live spikes connection.

To assist you quickly though. Have you got any fire walls turned on? and have you changed the spikeio script in any way?

please post this in the spinnaker user group with your reply.

regards
alan
